# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b04e174ca5d2c33ac47efc42b44b09abaa267b85711e96e59b860c4edff5184c9a40984dd5c39b5f6da227e797f578302a71128bf5bc4c27b3c75c71231c497a

test:
  secret_key_base: 9fa6329f853b4304a001037ced161604857f598b8fe6640f154a771b37c48d33d65b201451cfac743e49a34174ab26b18d59940cbcb874c6a4406822186805ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
